import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from '@next/third-parties/google'
 



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hotel Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.png" sizes="any" />
      <body className={inter.className}>{children}</body>
      <GoogleAnalytics gaId="G-9HG1ZSHDTQ" />
    </html>
  );
}
